AB = int(input("Довжина відрізка: "))
CD = int(input("Довжина відрізка: "))
EF = int(input("Довжина відрізка: "))
KL = int(input("Довжина відрізка: "))
MN = int(input("Довжина відрізка: "))
a = (('AB', AB), ('CD', CD), ('EF',EF), ('KL', KL), ('MN', MN))
b = dict(a)
s = len(b)
print("Кількість сторін многокутника: ", str(s))
c = max(b)
print("Найдовша сторона многокутника: ", str(c))
del(b['KL'])
print("Без KL: ", b)
print("AB =", AB, 'CD =', CD, 'EF = ', EF, 'KL = ', KL, "MN =", MN)
